予約詳細画面の表示方法変更対応
NS-APU/BabaCafe pull request #37
Opened 2023-06-21 06:16 UTC by KitajimaYoshiki

# 概要

予約詳細画面をダイアログからページ遷移に変更

※ web/app/src/pages/reservation/[id] 内にある index.svelteは作成中であるため、レビュー対象外としてください。

# 変更点
  
* (web)

  * reservation/index.svelte 内のDialogを削除
  * reservation/index.svelte 内のonClickをページ遷移に変更
  * reservationディレクトリへスクウェアブラケットディレクトリを追加

2023-06-21 08:48 UTC, T-Ishikawa-R commented on web/app/src/pages/reservation/index.svelte
> +          <Row on:click={ $goto(`./${item}`)}>
itemはObjectなので予約IDを指定するにはitem.idでしょうか？

2023-06-21 08:56 UTC, T-Ishikawa-R commented on web/app/src/pages/reservation/[id]/index.svelte
> +      return reservationRepository.findOne($params.id);
await がありません。

2023-06-21 08:56 UTC, T-Ishikawa-R commented on web/app/src/pages/reservation/[id]/index.svelte
> +    } catch (err) {
他と同様にUnauthorizedのケアをお願いします。

2023-06-22 00:17 UTC, YusukeWat commented on web/app/.routify/config.js
横からすみません。
確認させてください。
このファイル含む以下のファイルは、意図して削除するものでしょうか？

- web/app/.routify/config.js
- web/app/.routify/routes.js
- web/app/.routify/urlIndex.json
- web/app/.vscode/extensions.json

2023-06-22 00:21 UTC, T-Ishikawa-R commented on web/app/.routify/config.js
.gitignoreで除外されているものが誤ってコミットされているものだと思われます（おそらく.gitignoreの方が後から指定されたのかと推測）。
意図しない追跡対象になっており、削除して本来の.gitignoreの指定の通りなるようにしたものと思います。

2023-06-22 01:03 UTC, YusukeWat commented on web/app/.routify/config.js
現時点のdevブランチの .gitignore を確認すると /web/app/.routify や /web/app/.vscode が指定されていないようにみえます。
https://github.com/NS-APU/BabaCafe/blob/dev/.gitignore

このままマージしてしまうと諸々のファイルがdevブランチから消えてしまうことになり、webのビルドができなくならないか心配しています。

狙いどおりに調整するなら .gitignore の更新 + 各ファイルの差分解消 をしたほうがよいのでは・・？と思いました。
勘違いでしたらすみません。

2023-06-22 01:06 UTC, T-Ishikawa-R commented on web/app/.routify/config.js
.gitignoreは
https://github.com/NS-APU/BabaCafe/blob/dev/web/app/.gitignore
の方が対象です。
ビルドについてもGithub Actions のワークフローで問題ないことが確認できていると思います。

2023-06-22 01:24 UTC, YusukeWat commented on web/app/.routify/config.js
> ビルドについてもGithub Actions のワークフローで問題ないことが確認できていると思います。

おっしゃる通りですね、懸念は解消されました。
ありがとうございます。

2023-06-22 01:32 UTC, T-Ishikawa-R commented on web/app/src/pages/reservation/index.svelte
> +          <Row on:click={ $goto(`./${item}`)}>
2905616db8949ded697f37944e150b1a6348df4e で対応を確認しました。

2023-06-22 01:32 UTC, T-Ishikawa-R commented on web/app/src/pages/reservation/[id]/index.svelte
> +      return reservationRepository.findOne($params.id);
2905616db8949ded697f37944e150b1a6348df4e で対応を確認しました。

2023-06-22 01:32 UTC, T-Ishikawa-R commented on web/app/src/pages/reservation/[id]/index.svelte
> +    } catch (err) {
2905616db8949ded697f37944e150b1a6348df4e で対応を確認しました。

2023-06-22 01:33 UTC, T-Ishikawa-R approved these changes

2023-06-22 03:06 UTC, keis8221 requested changes
@KitajimaYoshiki 
私のダメダメコードを修正していただきありがとうございます！助かります！
余計なお世話かもしれませんが、２点コメントさせていただいたので、お手隙にお目通しいただけると幸いです🙏
確認されたら再度私にレビューリクエストを送信していただけますようお願いします。

2023-06-22 03:06 UTC, keis8221 commented on web/app/src/pages/reservation/[id]/index.svelte
> +  };
こちらの定数オブジェクトですが、web/app/src/constants/products配下に同じ内容のオブジェクトが既に存在していますね
DRY原則に従って、既に存在する定数を用いた方がコードの重複は防げると思いますがいかがでしょうか？？

2023-06-22 03:06 UTC, keis8221 commented on web/app/src/pages/reservation/[id]/index.svelte
> +          <!-- 生産者名 -->
綺麗にコードを書いてくださったおかげで、こちらのコメントが存在していなくても可読性は担保されていると思っております🙏
そのため、このコメントは削除しても良いかと思いますがいかがでしょうか？

2023-06-22 03:48 UTC, keis8221 commented
先に別のPRをマージしたことでコンフリクトが起きたため解消させていただきました。
以下の実行で再開発できるかと思います🙇‍♂️
```
git pull origin feat/reservation_detail
docker compose up -d --build
yarn all-dev
```

2023-06-22 04:32 UTC, KitajimaYoshiki commented
@keis8221 san
ご指摘ありがとうございます！
[id]/index.svelte はこの後対応していくので、頂いた指摘も反映していきます。

競合の部分も解消したので、ご確認お願い致します。

2023-06-22 04:49 UTC, T-Ishikawa-R commented on web/app/src/pages/reservation/[id]/index.svelte
> +            "https://girlydrop.com/wp-content/uploads/post/p5774.jpg"}
元の実装からであり、出品一覧画面でも同様ですが、
https://girlydrop.com
の利用規約では画像への直リンクが禁止されており、利用規約違反となっています。
予約詳細画面は現段階では仮実装状態だと思いますので、本対応時には解消をお願いします。
![image](https://github.com/NS-APU/BabaCafe/assets/91717473/8c4a56f7-2dbb-4f29-a1f4-0ca494402a7e)

2023-06-22 05:18 UTC, keis8221 commented on web/app/src/pages/reservation/[id]/index.svelte
> +            "https://girlydrop.com/wp-content/uploads/post/p5774.jpg"}
@T-Ishikawa-R 
ありがとうございます！
こちら適切な画像を本プロジェクトの内に保持させて使い回す方向で対応しようと思います🙏

2023-06-22 05:19 UTC, keis8221 approved these changes
@KitajimaYoshiki 
失礼いたしました🙏
レビュー対象外というのを忘れてレビューしてしまっておりました。大変申し訳ございません🙇‍♂️
LGTMです！

2023-06-22 05:19 UTC, merged