予約取り消し機能の実装
NS-APU/BabaCafe pull request #46
Opened 2023-07-11 03:01 UTC by KitajimaYoshiki

# 概要

予約詳細画面への予約取り消しボタンの追加と、ステータス変更機能の実装

# 変更点
  
* (web)

  * 取り消しボタンの実装
  * バックエンド側実装のAPI呼び出し
  * 編集ボタンの実装

* (back)

  * 出品残量の更新
  * ステータス変更 pakking -> canceled

# 制約

編集ボタンはボタン配置のみの実装で、編集機能は未実装。

2023-07-11 23:54 UTC, T-Ishikawa-R requested changes

2023-07-11 23:54 UTC, T-Ishikawa-R commented on web/app/src/pages/reservation/[id]/index.svelte
> +          <Button class="  mr-2 w-[150px] rounded-full px-4 py-2" color="secondary" variant="raised">
予約内容編集については優先度が異なるため、機能しないボタンを入れておくのは避けたいです。
コメントアウトや削除で対応をお願いします。

2023-07-11 23:55 UTC, keis8221 approved these changes
動作確認もバッチリでした！
LGTMです！！

石川さんのレビューを修正して、approveをもらい次第マージさせていただきます🙏

2023-07-12 00:02 UTC, T-Ishikawa-R commented
今回の対応範囲ではありませんが、予約取り消ししたときのステータスのラベルが「キャンセル」であることについて、直前の予約取り消しのダイアログで「キャンセル」/「取り消し」の選択肢となっていて、ステータスのラベルが「キャンセル」だとユーザーからみると紛らわしいなと使ってみて感じました。ダイアログの選択肢が紛らわしいのもありますが、操作とステータスが一致するようにステータスのラベルは「取り消し」の方が良いかと思います。
![image](https://github.com/NS-APU/BabaCafe/assets/91717473/34ffc2c6-4edf-4691-ab7f-5a2f2646bbe2)
![image](https://github.com/NS-APU/BabaCafe/assets/91717473/eeaf936c-3945-48ae-938a-76866f6506cb)

2023-07-12 07:01 UTC, YusukeWat commented on web/app/src/pages/reservation/[id]/index.svelte
> +          <Button class="  mr-2 w-[150px] rounded-full px-4 py-2" color="secondary" variant="raised">
ご指摘ありがとうございます。
予約編集は本対応より優先度が下がるため、一旦コメントアウトしました。
北嶋さんが丁寧に配置調整をしてくれたので消してしまうのはもったいなく。

2023-07-12 07:05 UTC, YusukeWat commented
> 今回の対応範囲ではありませんが、予約取り消ししたときのステータスのラベルが「キャンセル」であることについて、直前の予約取り消しのダイアログで「キャンセル」/「取り消し」の選択肢となっていて、ステータスのラベルが「キャンセル」だとユーザーからみると紛らわしいなと使ってみて感じました。ダイアログの選択肢が紛らわしいのもありますが、操作とステータスが一致するようにステータスのラベルは「取り消し」の方が良いかと思います。 ![image](https://user-images.githubusercontent.com/91717473/252820308-34ffc2c6-4edf-4691-ab7f-5a2f2646bbe2.png) ![image](https://user-images.githubusercontent.com/91717473/252820343-eeaf936c-3945-48ae-938a-76866f6506cb.png)

こちらについては「予約取り消し」でラベル名を修正しました。
予約一覧の表で見たときに「取り消し」よりわかりやすかったためです。
カード化したときに改めて文言は精査できればと思います。
![image](https://github.com/NS-APU/BabaCafe/assets/57512638/7fbdcb59-14e7-41a4-a700-118c48b7cdaf)

関連して、ステータス変更後の表示メッセージが「予約をキャンセルしました。」と紛らわしかったので併せて修正しました。

2023-07-12 07:42 UTC, T-Ishikawa-R commented on web/app/src/pages/reservation/[id]/index.svelte
> +          <Button class="  mr-2 w-[150px] rounded-full px-4 py-2" color="secondary" variant="raised">
対応を確認しました。ありがとうございます。

2023-07-12 07:44 UTC, T-Ishikawa-R commented
@YusukeWat 

> こちらについては「予約取り消し」でステータス名を修正しました。
> 予約一覧の表で見たときに「取り消し」よりわかりやすかったためです。

文言の修正ありがとうございます。「予約取り消し」としてよりわかりやすくなったと思います。

2023-07-12 07:44 UTC, T-Ishikawa-R approved these changes

2023-07-12 15:57 UTC, keis8221 commented
文言もいい感じに修正していただきありがとうございます！
マージします！

2023-07-12 15:57 UTC, merged