出品とりやめ機能の実装
NS-APU/BabaCafe pull request #49
Opened 2023-07-24 03:59 UTC by YoshidaYuma

# 概要

出品とりやめボタンの追加と、論理削除の実装

# 変更点
  
* (web)

  * 出品とりやめボタンの実装
    * 予約が1回でもあった時点で表示しないように制御
  * 確認ダイアログの実装
  * バックエンド側実装のAPI呼び出し
  * エラーハンドリングをメソッドに変更（fetchProduct()とcanceled()からも呼べるようにするため）

* (back)

  * DELETE /products/:productId/canceled API新規作成
    * 論理削除の実行

2023-07-24 07:08 UTC, T-Ishikawa-R commented on server/app/src/product/product.controller.ts
> +  @Delete('/:productId/canceled')
REST APIなのでHTTPメソッドがDELETEの場合は削除に該当する処理が期待されますが、メソッド名はupdateXXXとなっており更新を連想してしまうため、命名について検討をお願いします。

2023-07-24 07:10 UTC, T-Ishikawa-R commented on server/app/src/product/product.service.ts
> +    if (!product) {
処理に時間がかかるため段階的に分離するようなことがありますが、L78とL81はそのようなこともないため、ORで条件をまとめたほうが良いかと思います。

2023-07-24 07:23 UTC, T-Ishikawa-R requested changes

2023-07-24 07:23 UTC, T-Ishikawa-R commented on web/app/src/pages/product/[id]/index.svelte
> +      canCanceled = !(await reservationRepository.allReservations()).some(
予約の総数が数万件規模になってくるとこの処理の遅さが際立ってきます。
大量のデータからあるデータを探すのはそれを得意とするDBに任せましょう。

ここでのキャンセル可否についての提案になりますが、product.service.tsのgetProductにおいてfindOneするときにrelationsでreservationsをtrueにしてはいかがでしょうか？そうすることで紐づく予約情報も一緒に取得できるため、product.reservationsの配列データの有無で判断がつくようになるかと思います。

2023-07-24 07:27 UTC, T-Ishikawa-R requested changes

2023-07-24 07:27 UTC, T-Ishikawa-R commented on web/app/src/pages/product/[id]/index.svelte
> +          message: '商品の更新に失敗しました。開発者へお問い合わせください。',
出品の取りやめに失敗したときにもBad Requestが返る可能性がありますが、そのときのメッセージは「更新」で良いでしょうか？

2023-07-24 08:01 UTC, YoshidaYuma commented on web/app/src/pages/product/[id]/index.svelte
> +      canCanceled = !(await reservationRepository.allReservations()).some(
ご指摘ありがとうございます。そのように修正いたします。

2023-07-24 08:04 UTC, YoshidaYuma commented on web/app/src/pages/product/[id]/index.svelte
> +          message: '商品の更新に失敗しました。開発者へお問い合わせください。',
今後実装されるであろう編集機能もBad Requestを返すだろうという想定を踏まえ、「商品情報の操作に失敗しました。・・・」でいかがでしょうか？

2023-07-24 08:08 UTC, T-Ishikawa-R commented on web/app/src/pages/product/[id]/index.svelte
> +          message: '商品の更新に失敗しました。開発者へお問い合わせください。',
それもひとつの策だと思いますし、操作内容を引数にとりテンプレートリテラルで埋めるのもありだと思います。
どのようにするかはお任せします。

2023-07-25 01:04 UTC, YoshidaYuma commented on server/app/src/product/product.controller.ts
> +  @Delete('/:productId/canceled')
メソッド名を"cancelProduct()"に変更しました。

2023-07-25 01:05 UTC, YoshidaYuma commented on server/app/src/product/product.service.ts
> +    if (!product) {
L78とL81の条件を１行にORでまとめました。

2023-07-25 01:06 UTC, YoshidaYuma commented on web/app/src/pages/product/[id]/index.svelte
> +          message: '商品の更新に失敗しました。開発者へお問い合わせください。',
操作内容を引数にとりテンプレートリテラルでエラーメッセージを表示するように修正しました。

2023-07-25 01:17 UTC, T-Ishikawa-R commented on web/app/src/pages/product/[id]/index.svelte
> +          message: '商品の更新に失敗しました。開発者へお問い合わせください。',
handleErrorのdefaultのメッセージで「商品の取得」を${operation}にしなかった理由はありますか？
メッセージにおける操作名が入る箇所はすべてテンプレートリテラルで埋めるようになれば、fetchProductのoperationが空文字になっているところも「商品の取得」になると思います。

2023-07-25 01:28 UTC, T-Ishikawa-R commented on server/app/src/product/product.controller.ts
> +  @Delete('/:productId/canceled')
d3a7a2c での修正を確認しました。OKです。

一般的にcancelの処理の中にはステータスを変更（更新）することもあり、そのような場合はPUTが使われたりします。今回はcancelによって削除されるため、ここでのcancelがDELETEに相当するのでこの命名でも良いですが、混同することを避けるのであれば、deleteProductやremoveProductといった命名にすることでコードの意図することがシンプルにわかるようにもなりますね。

2023-07-25 01:28 UTC, T-Ishikawa-R commented on server/app/src/product/product.service.ts
> +    if (!product) {
d3a7a2c での修正を確認しました。OKです。

2023-07-25 01:28 UTC, T-Ishikawa-R commented on web/app/src/pages/product/[id]/index.svelte
> +      canCanceled = !(await reservationRepository.allReservations()).some(
d3a7a2c での修正を確認しました。OKです。

2023-07-25 01:33 UTC, YusukeWat commented on server/app/src/product/product.controller.ts
> +  @Delete('/:productId/canceled')
横から失礼します。

細かいですがAPIのパスについても一考の余地ありかと。
HTTPメソッドがDELETEに相当しうる機能が今後想定されなければ `@Delete('/:productId')` でもよいのでは？
「/canceled」 が冗長的な気がして。。

2023-07-25 01:35 UTC, YoshidaYuma commented on server/app/src/product/product.controller.ts
> +  @Delete('/:productId/canceled')
コメントありがとうございます。
確かにdelete等のほうがシンプルに動作が分かりやすいですね。。
こちらの方も合わせて変更しておきます

2023-07-25 01:38 UTC, YoshidaYuma commented on server/app/src/product/product.controller.ts
> +  @Delete('/:productId/canceled')
> HTTPメソッドがDELETEに相当しうる機能が今後想定されなければ @Delete('/:productId') でもよいのでは？

コメントありがとうございます。
確かに冗長的な気がするのでこちらも変更しておきます。

2023-07-25 01:51 UTC, YoshidaYuma commented on web/app/src/pages/product/[id]/index.svelte
> +          message: '商品の更新に失敗しました。開発者へお問い合わせください。',
https://github.com/NS-APU/BabaCafe/pull/49/commits/61c0dc4053e14ed3863098702ca1ee18294a1dd8
こちらのcommitで上記修正しました。

2023-07-25 01:54 UTC, YoshidaYuma commented on server/app/src/product/product.controller.ts
> +  @Delete('/:productId/canceled')
https://github.com/NS-APU/BabaCafe/pull/49/commits/71032749617e0537ca1d568e7460a7e0916629a7
こちらのcommitでdeleteProductに命名変更しました。

https://github.com/NS-APU/BabaCafe/pull/49/commits/61c0dc4053e14ed3863098702ca1ee18294a1dd8
こちらのcommitでAPIのパスを修正しました。

（commit分かれてしまい申し訳ありません。。）

2023-07-25 05:59 UTC, T-Ishikawa-R commented on server/app/src/product/product.controller.ts
> +  @Delete('/:productId/canceled')
対応を確認しました。DELETEメソッドにしたのも良いと思います。

2023-07-25 06:00 UTC, T-Ishikawa-R commented on web/app/src/pages/product/[id]/index.svelte
> +          message: '商品の更新に失敗しました。開発者へお問い合わせください。',
対応を確認しました。OKです。

2023-07-25 06:00 UTC, T-Ishikawa-R approved these changes

2023-07-25 06:00 UTC, T-Ishikawa-R approved these changes

2023-07-25 07:30 UTC, Mirenk commented
すいません，これからコードを読むのと動作確認させていただきますが，お手すきであればhttps://github.com/NS-APU/BabaCafe/pull/50 をマージした状態での削除を確認していただけないでしょうか？(大丈夫ではあると思うのですが…)

2023-07-25 08:00 UTC, Mirenk approved these changes
確認いたしました！問題ありません．
https://github.com/NS-APU/BabaCafe/pull/50 マージ後の動作確認がこちらでも取れたので，マージさせていただきます．

2023-07-25 08:00 UTC, merged