物流業者向け物流設定画面にて画面の表示、集荷配送方法の変更、路線の追加の機能を実装
NS-APU/BabaCafe pull request #58
Opened 2023-08-25 08:52 UTC by YoshidaYuma

# 概要
物流業者向け物流設定画面にて以下の3つの機能を実装した。
- 画面の表示
画面表示後、集荷配送方法の状態、路線の一覧、便の一覧が表示できる。
※路線と便はそれぞれアコーディオンを開くことで表示できる。

- 集荷配送方法の変更
集荷配送方法の編集ボタン押下後、変更ダイアログにより編集することが出来る。

- 路線の追加
路線追加ボタン押下後、路線追加ダイアログにて路線名を入力することで路線を追加することが出来る。

# 制限事項
以下項目は本PRでは対象外としているためボタンは用意しているがdisableにしている。
- 路線の編集
- 路線の削除
- 便の追加
- 便の編集
- 便の削除
- 以下のPRで共通なエラー(handleError)を統一化する変更がされているが、そのPRがdevにMergeされる前に本PRを作成したため、こちら新たに実装したhandleErrorは統一化されていない。そのためその統一化対応がMergeされてから変更を取り込む。（Dialogの分離対応も以下PRで行われているが、そちらもMergeされてから行う。）
https://github.com/NS-APU/BabaCafe/pull/57

# 動作確認内容
- 物流業者アカウントでログイン後、物流設定画面を開くことで集荷配送方法の状態、路線の一覧のアコーディオンが表示されることを確認。
- 各路線のアコーディオンを開くことで、便の一覧のアコーディオンが表示されることを確認。
- 各便のアコーディオンを開くことで、衝撃度、最大積載量、時刻表が表示されることを確認。
- 集荷配送方法の状態が”集荷先や配送先に直接伺う”の場合、巡回経路の設定部分は表示されないことを確認。
- 集荷配送方法を変更した場合、問題なく変更されることを確認。
- 集荷配送方法変更ダイアログのラジオボタンの初期選択が、現在設定されているものになっていることを確認。
- 路線を追加した場合、入力した名前の路線が追加されることを確認。

# 備考
PRが大きくなってしまい申し訳ありません。。

2023-08-28 03:57 UTC, T-Ishikawa-R requested changes

2023-08-28 03:57 UTC, T-Ishikawa-R commented on web/app/src/pages/logistics/setting/_components/LogisticsSettingForm.svelte
> +            <div class="justify-left ml-8 flex">
SMUI の Selection dialog を使ってください。
https://sveltematerialui.com/demo/dialog/

以下のような感じにリファクタリングできるかと思います。
```
<Content>
  <List radioList>
    <Item>
      <Graphic>
        <Radio bind:group={logisticsSetting.deliveryType} value={DELIVERY_TYPE.route} />
      </Graphic>
      <Text>{MESSAGE_OF_DELIVERY_TYPE.route}</Text>
    </Item>
    <Item>
      <Graphic>
        <Radio bind:group={logisticsSetting.deliveryType} value={DELIVERY_TYPE.direct} />
      </Graphic>
      <Text>{MESSAGE_OF_DELIVERY_TYPE.direct}</Text>
    </Item>
  </List>
</Content>
````

2023-08-28 04:30 UTC, T-Ishikawa-R commented on web/app/src/pages/logistics/setting/_components/LogisticsSettingForm.svelte
> +            <input type="text" class="justfy-center mx-3 flex" bind:value={routeName} />
ダイアログ内の入力からフォーカスを外すと入力箇所が見えなくなります。
![image](https://github.com/NS-APU/BabaCafe/assets/91717473/a2ea9515-8428-4e20-805f-feda873bd32d)

SMUI の TextField を使ってはどうでしょうか？
https://sveltematerialui.com/demo/textfield/

2023-08-28 04:46 UTC, T-Ishikawa-R commented on web/app/src/pages/logistics/setting/_components/LogisticsSettingForm.svelte
> +  <div class="grid">
grid container text-lg の３つのdivは、これらのclassが有効に作用できていないので、ひとつのclassなしのdivにまとめられるかと思います。

2023-08-28 05:13 UTC, T-Ishikawa-R commented on web/app/src/pages/logistics/setting/_components/LogisticsSettingForm.svelte
> +        <div
他での見出し同様にh1にしなかった理由はありますか？

2023-08-28 05:14 UTC, T-Ishikawa-R commented on web/app/src/pages/logistics/setting/_components/LogisticsSettingForm.svelte
> +        {#if deliveryType === DELIVERY_TYPE.route}
テキスト部分の差異のみなので以下でいかがでしょうか？

```
      <p class="mt-4">
        {deliveryType === DELIVERY_TYPE.route ? MESSAGE_OF_DELIVERY_TYPE.route : MESSAGE_OF_DELIVERY_TYPE.direct}
      </p>
```

2023-08-28 05:14 UTC, T-Ishikawa-R commented on web/app/src/pages/logistics/setting/_components/LogisticsSettingForm.svelte
> +        <p class="mt-4" />
こちらは不要かと思います。

2023-08-28 05:15 UTC, T-Ishikawa-R commented on web/app/src/pages/logistics/setting/_components/LogisticsSettingForm.svelte
> +          <p class="mt-3 border-l-8 border-solid border-l-primary bg-[#f4f4f4] px-3 py-2 text-lg text-[#494949]">
巡回経路の設定部分をdivでマークアップしてはいかがでしょうか？

2023-08-28 05:16 UTC, T-Ishikawa-R commented on web/app/src/pages/logistics/setting/_components/LogisticsSettingForm.svelte
> +          <div style="display: flex; justify-content: center">
styleではなくtailwindでclass指定してください。

2023-08-28 05:26 UTC, T-Ishikawa-R commented on web/app/src/pages/logistics/setting/_components/LogisticsSettingForm.svelte
> +              <Button class="w-[150px]  rounded-full px-4 py-2" color="secondary" variant="raised" action="createRoute">
路線名が未入力の場合はdisabledにする必要があります。

2023-08-28 06:19 UTC, T-Ishikawa-R commented on web/app/src/pages/logistics/setting/_components/LogisticsRouteAccordion.svelte
> +  <Accordion class="mt-4 outline outline-1 outline-offset-2 outline-[#000000]">
アウトラインが無いほうがUIとしてはスッキリすると思いますが、アウトラインを設けた理由などありましたら教えてください。

2023-08-28 06:19 UTC, T-Ishikawa-R commented on web/app/src/pages/logistics/setting/_components/LogisticsRouteAccordion.svelte
> +        <div style="display: flex; justify-content: center">
styleではなくtailwindでclass指定してください。

2023-08-28 06:21 UTC, T-Ishikawa-R commented on web/app/src/pages/logistics/setting/_components/LogisticsTripAccordion.svelte
> +<div class="ml-6">
マージンを取らなくとも十分に余裕があるように思います。

2023-08-28 06:22 UTC, T-Ishikawa-R commented on web/app/src/pages/logistics/setting/_components/LogisticsTripAccordion.svelte
> +  <Accordion class="mr-2 mt-4 outline outline-1 outline-offset-2 outline-[#000000]">
上方向のマージンは必要と思いますが、右方向のマージンはなくとも十分に余裕があるように思います。

2023-08-28 06:22 UTC, T-Ishikawa-R commented on web/app/src/pages/logistics/setting/_components/LogisticsTripAccordion.svelte
> +  <Accordion class="mr-2 mt-4 outline outline-1 outline-offset-2 outline-[#000000]">
こちらもアウトラインが無いほうがUIとしてはスッキリすると思いますが、アウトラインを設けた理由などありましたら教えてください。

2023-08-28 06:38 UTC, T-Ishikawa-R commented on web/app/src/pages/logistics/setting/_components/LogisticsTripAccordion.svelte
> +            <p>{trip.shockLevel}</p>
数値で扱いますが、表示については目安となる抽象的表現（とても強い、強い、弱い、とても弱い）となる文字列になります。

2023-08-28 06:55 UTC, T-Ishikawa-R commented on web/app/src/pages/logistics/setting/_components/LogisticsTripAccordion.svelte
> +  let panel1Open = false;
サンプルの名残で不要かと思います。

2023-08-28 07:20 UTC, KitajimaYoshiki commented on web/app/src/pages/logistics/setting/_components/LogisticsTripAccordion.svelte
> +  <Accordion class="mr-2 mt-4 outline outline-1 outline-offset-2 outline-[#000000]">
現在SMUIのAccordion使用していますが、以前はHTMLのdetailsを使用して実装していたので、その名残です（HTMLのほうは外枠なかったので、Outlineで区画をわかりやすくする目的で実装していました）。
私のほうで確認しましたが、SMUIに変更した際、Outlineが無くても区画がわかりやすくなっていたので、AccodionのOutlineは削除します。ご指摘ありがとうございます。

上のほうのAccodion実装に関する指摘も同様の対応です。よろしくお願いします。

2023-08-28 07:22 UTC, T-Ishikawa-R commented on web/app/src/pages/logistics/setting/_components/LogisticsRouteAccordion.svelte
> +        {route.name}
アコーディオンの開閉を表示してみてはいかがでしょうか（LogisticsTripAccordionも同様）？

以下はその例です。

```
<script>
$: panelOpen = false;
</script>

<Accordion >
  <Panel >
    <Header
      on:click={() => {
        panelOpen = !panelOpen;
      }}
    >
      {#if panelOpen}
        <span class="material-icons inline-block align-middle">expand_more</span>
      {:else}
        <span class="material-icons inline-block align-middle">chevron_right</span>
      {/if}
      {route.name}
      <span slot="icon">
        省略
      </span>
    </Header>
```

![capture](https://github.com/NS-APU/BabaCafe/assets/91717473/8593f3d7-88b8-4a1b-bf1a-5a496c2280df)

2023-08-28 08:02 UTC, KitajimaYoshiki commented on web/app/src/pages/logistics/setting/_components/LogisticsSettingForm.svelte
> +        <div
理由は特にありません。h1に修正します。

2023-08-29 00:34 UTC, T-Ishikawa-R commented on web/app/src/pages/logistics/setting/_components/LogisticsTripAccordion.svelte
> +            <p class="mt-2">{trip.capacity}</p>
単位となる「予約」の表記が必要かと思います。

2023-08-29 00:39 UTC, T-Ishikawa-R commented on web/app/src/pages/logistics/setting/_components/LogisticsTripAccordion.svelte
> +          <DataTable class="mb-3 mt-3" table$aria-label="People list" style="max-width: 100%;">
table$aria-labelの指定は正しいですか？

2023-08-29 00:41 UTC, T-Ishikawa-R commented on web/app/src/pages/logistics/setting/_components/LogisticsTripAccordion.svelte
> +          <DataTable class="mb-3 mt-3" table$aria-label="People list" style="max-width: 100%;">
mb-3 mt-3 はつまり my-3 ですね。

2023-08-29 00:42 UTC, T-Ishikawa-R commented on web/app/src/pages/logistics/setting/_components/LogisticsTripAccordion.svelte
> +          <DataTable class="mb-3 mt-3" table$aria-label="People list" style="max-width: 100%;">
style="max-width: 100%;" は tailwind 表現しましょう。

2023-08-29 00:59 UTC, T-Ishikawa-R commented on web/app/src/pages/logistics/setting/_components/LogisticsTripAccordion.svelte
> +                  <Cell>{timetable.stop}</Cell>
ヘッダーが中央寄せになっているのであればデータに中央寄せにして揃えたほうが良いかと思います。

2023-08-29 02:27 UTC, YoshidaYuma commented on web/app/src/pages/logistics/setting/_components/LogisticsTripAccordion.svelte
> +          <DataTable class="mb-3 mt-3" table$aria-label="People list" style="max-width: 100%;">
サンプルの残りですので削除しておきます！

2023-08-29 03:50 UTC, YoshidaYuma commented on web/app/src/pages/logistics/setting/_components/LogisticsSettingForm.svelte
> +            <div class="justify-left ml-8 flex">
https://github.com/NS-APU/BabaCafe/pull/58/commits/b7991978a21fe94faff84e8276e83b507d811d69
上記コミットにてリファクタリングを行いました。

2023-08-29 03:52 UTC, YoshidaYuma commented on web/app/src/pages/logistics/setting/_components/LogisticsSettingForm.svelte
> +            <input type="text" class="justfy-center mx-3 flex" bind:value={routeName} />
https://github.com/NS-APU/BabaCafe/commit/b7991978a21fe94faff84e8276e83b507d811d69
上記コミットにてSMUIのTextFieldを使うように修正しました。

2023-08-29 03:54 UTC, YoshidaYuma commented on web/app/src/pages/logistics/setting/_components/LogisticsSettingForm.svelte
> +  <div class="grid">
https://github.com/NS-APU/BabaCafe/commit/b7991978a21fe94faff84e8276e83b507d811d69
上記コミットにて、ひとつのdivにまとめるように修正しました。

2023-08-29 03:56 UTC, YoshidaYuma commented on web/app/src/pages/logistics/setting/_components/LogisticsSettingForm.svelte
> +        <div
https://github.com/NS-APU/BabaCafe/commit/b7991978a21fe94faff84e8276e83b507d811d69
上記コミットでh1に修正したものをPUSHしました。

2023-08-29 03:57 UTC, YoshidaYuma commented on web/app/src/pages/logistics/setting/_components/LogisticsSettingForm.svelte
> +        {#if deliveryType === DELIVERY_TYPE.route}
コメントありがとうございます。
https://github.com/NS-APU/BabaCafe/commit/b7991978a21fe94faff84e8276e83b507d811d69
上記コミットにてそのように修正しました。

2023-08-29 03:58 UTC, YoshidaYuma commented on web/app/src/pages/logistics/setting/_components/LogisticsSettingForm.svelte
> +        <p class="mt-4" />
https://github.com/NS-APU/BabaCafe/commit/b7991978a21fe94faff84e8276e83b507d811d69
上記コミットにて削除しました。

2023-08-29 04:00 UTC, YoshidaYuma commented on web/app/src/pages/logistics/setting/_components/LogisticsSettingForm.svelte
> +          <p class="mt-3 border-l-8 border-solid border-l-primary bg-[#f4f4f4] px-3 py-2 text-lg text-[#494949]">
https://github.com/NS-APU/BabaCafe/commit/b7991978a21fe94faff84e8276e83b507d811d69
上記コミットにて、divでマークアップを行いました。

2023-08-29 04:01 UTC, YoshidaYuma commented on web/app/src/pages/logistics/setting/_components/LogisticsSettingForm.svelte
> +          <div style="display: flex; justify-content: center">
https://github.com/NS-APU/BabaCafe/commit/b7991978a21fe94faff84e8276e83b507d811d69
上記コミットにて、tailwindに修正しました。

2023-08-29 04:04 UTC, YoshidaYuma commented on web/app/src/pages/logistics/setting/_components/LogisticsSettingForm.svelte
> +              <Button class="w-[150px]  rounded-full px-4 py-2" color="secondary" variant="raised" action="createRoute">
https://github.com/NS-APU/BabaCafe/commit/b7991978a21fe94faff84e8276e83b507d811d69
上記コミットにて、routeNameの有無で表示非表示を切り替えるようにしました。

2023-08-29 04:07 UTC, YoshidaYuma commented on web/app/src/pages/logistics/setting/_components/LogisticsRouteAccordion.svelte
> +        <div style="display: flex; justify-content: center">
https://github.com/NS-APU/BabaCafe/commit/b7991978a21fe94faff84e8276e83b507d811d69
上記コミットにてtailwindで記載するように修正しました。

2023-08-29 04:08 UTC, YoshidaYuma commented on web/app/src/pages/logistics/setting/_components/LogisticsTripAccordion.svelte
> +<div class="ml-6">
https://github.com/NS-APU/BabaCafe/commit/b7991978a21fe94faff84e8276e83b507d811d69
上記コミットにてマージンの記載を削除しました。

2023-08-29 04:09 UTC, YoshidaYuma commented on web/app/src/pages/logistics/setting/_components/LogisticsTripAccordion.svelte
> +  <Accordion class="mr-2 mt-4 outline outline-1 outline-offset-2 outline-[#000000]">
https://github.com/NS-APU/BabaCafe/commit/b7991978a21fe94faff84e8276e83b507d811d69
上記コミットにて右方向のマージンを削除しました。

2023-08-29 04:10 UTC, YoshidaYuma commented on web/app/src/pages/logistics/setting/_components/LogisticsTripAccordion.svelte
> +  <Accordion class="mr-2 mt-4 outline outline-1 outline-offset-2 outline-[#000000]">
https://github.com/NS-APU/BabaCafe/commit/b7991978a21fe94faff84e8276e83b507d811d69
上記コミットにてアウトラインを削除したものをPUSHしました。

2023-08-29 04:14 UTC, YoshidaYuma commented on web/app/src/pages/logistics/setting/_components/LogisticsTripAccordion.svelte
> +            <p>{trip.shockLevel}</p>
https://github.com/NS-APU/BabaCafe/commit/b7991978a21fe94faff84e8276e83b507d811d69
上記コミットにて衝撃の数値によって「とても強い、強い、弱い、とても弱い」が表示されるように修正しました。

2023-08-29 04:15 UTC, YoshidaYuma commented on web/app/src/pages/logistics/setting/_components/LogisticsTripAccordion.svelte
> +  let panel1Open = false;
こちらはアコーディオンの開閉を表示するために残しておきます。

2023-08-29 04:16 UTC, YoshidaYuma commented on web/app/src/pages/logistics/setting/_components/LogisticsRouteAccordion.svelte
> +        {route.name}
https://github.com/NS-APU/BabaCafe/commit/b7991978a21fe94faff84e8276e83b507d811d69
アコーディオンの開閉が表示されるように、頂いた例を参考に上記コミットにて修正しました。

2023-08-29 04:18 UTC, YoshidaYuma commented on web/app/src/pages/logistics/setting/_components/LogisticsTripAccordion.svelte
> +            <p class="mt-2">{trip.capacity}</p>
https://github.com/NS-APU/BabaCafe/pull/58/commits/4d4019194bd36c99d1fbed918d756e40c0ce464e
上記コミットにて「予約」の表記を追加しました。

2023-08-29 04:18 UTC, YoshidaYuma commented on web/app/src/pages/logistics/setting/_components/LogisticsTripAccordion.svelte
> +          <DataTable class="mb-3 mt-3" table$aria-label="People list" style="max-width: 100%;">
https://github.com/NS-APU/BabaCafe/commit/4d4019194bd36c99d1fbed918d756e40c0ce464e
上記コミットにて削除しました。

2023-08-29 04:20 UTC, YoshidaYuma commented on web/app/src/pages/logistics/setting/_components/LogisticsTripAccordion.svelte
> +          <DataTable class="mb-3 mt-3" table$aria-label="People list" style="max-width: 100%;">
https://github.com/NS-APU/BabaCafe/commit/4d4019194bd36c99d1fbed918d756e40c0ce464e
上記コミットにて my-3 に修正しました。

2023-08-29 04:21 UTC, YoshidaYuma commented on web/app/src/pages/logistics/setting/_components/LogisticsTripAccordion.svelte
> +          <DataTable class="mb-3 mt-3" table$aria-label="People list" style="max-width: 100%;">
https://github.com/NS-APU/BabaCafe/commit/4d4019194bd36c99d1fbed918d756e40c0ce464e
上記コミットにて max-w-full に修正しました。

2023-08-29 04:22 UTC, YoshidaYuma commented on web/app/src/pages/logistics/setting/_components/LogisticsTripAccordion.svelte
> +                  <Cell>{timetable.stop}</Cell>
https://github.com/NS-APU/BabaCafe/commit/4d4019194bd36c99d1fbed918d756e40c0ce464e
上記コミットにて、データも中央寄せになるように修正しました。

2023-08-29 04:33 UTC, YoshidaYuma commented
https://github.com/NS-APU/BabaCafe/pull/57
上記PRがdevにmergeされたので、本ブランチにも取り込みました。
その際handleErrorの統一化対応も取り込んだので、下記コミットにて物流業者向け物流設定画面のエラー処理も統一化されたhandleErrorを使用するように修正しました。
https://github.com/NS-APU/BabaCafe/pull/58/commits/5dd0609188ba1141be019d273b6f07d183514dc9

2023-08-29 05:58 UTC, T-Ishikawa-R commented on web/app/src/pages/logistics/setting/_components/LogisticsSettingForm.svelte
> +            <div class="justify-left ml-8 flex">
修正を確認しました。OKです。

2023-08-29 06:01 UTC, T-Ishikawa-R commented on web/app/src/pages/logistics/setting/_components/LogisticsSettingForm.svelte
> +            <input type="text" class="justfy-center mx-3 flex" bind:value={routeName} />
TextFieldはContentの領域にいれるようにしてください。
また、UIを見ると入力の部分（Content）とボタンの領域（Action）が近接しているように思います。
TextFieldの下部に5ピクセルほどマージンをとると良いのではないかと思います。

2023-08-29 06:02 UTC, T-Ishikawa-R commented on web/app/src/pages/logistics/setting/_components/LogisticsSettingForm.svelte
> +  <div class="grid">
修正を確認しました。OKです。

2023-08-29 06:11 UTC, T-Ishikawa-R commented on web/app/src/pages/logistics/setting/_components/LogisticsSettingForm.svelte
> +        <div
h1で設定するclassが親のdivについているように思います。それと見出し文字列をspanで囲ったほうが他のアコーディオンの見出しなどど色味が揃うように思います。
また、フォーマットでclassのオーダー順が効いておらず、(root)/lint.readme.md の設定がされているかを確認してみてください。

2023-08-29 06:13 UTC, T-Ishikawa-R commented on web/app/src/pages/logistics/setting/_components/LogisticsSettingForm.svelte
> +        {#if deliveryType === DELIVERY_TYPE.route}
修正方法自体はOKですが、pタグを直前のdivの中に入れてあげたほうが良いかと思います。

2023-08-29 06:13 UTC, T-Ishikawa-R commented on web/app/src/pages/logistics/setting/_components/LogisticsSettingForm.svelte
> +        <p class="mt-4" />
修正を確認しました。OKです。

2023-08-29 06:14 UTC, T-Ishikawa-R commented on web/app/src/pages/logistics/setting/_components/LogisticsSettingForm.svelte
> +          <p class="mt-3 border-l-8 border-solid border-l-primary bg-[#f4f4f4] px-3 py-2 text-lg text-[#494949]">
修正を確認しました。OKです。

2023-08-29 06:15 UTC, T-Ishikawa-R commented on web/app/src/pages/logistics/setting/_components/LogisticsSettingForm.svelte
> +              <Button class="w-[150px]  rounded-full px-4 py-2" color="secondary" variant="raised" action="createRoute">
修正を確認しました。OKです。

2023-08-29 06:16 UTC, T-Ishikawa-R commented on web/app/src/pages/logistics/setting/_components/LogisticsRouteAccordion.svelte
> +        <div style="display: flex; justify-content: center">
修正を確認しました。OKです。

2023-08-29 06:17 UTC, T-Ishikawa-R commented on web/app/src/pages/logistics/setting/_components/LogisticsTripAccordion.svelte
> +  <Accordion class="mr-2 mt-4 outline outline-1 outline-offset-2 outline-[#000000]">
修正を確認しました。OKです。

2023-08-29 06:18 UTC, T-Ishikawa-R commented on web/app/src/pages/logistics/setting/_components/LogisticsTripAccordion.svelte
> +  <Accordion class="mr-2 mt-4 outline outline-1 outline-offset-2 outline-[#000000]">
修正を確認しました。OKです。

2023-08-29 06:19 UTC, T-Ishikawa-R commented on web/app/src/pages/logistics/setting/_components/LogisticsTripAccordion.svelte
> +            <p>{trip.shockLevel}</p>
修正を確認しました。OKです。

2023-08-29 06:21 UTC, T-Ishikawa-R commented on web/app/src/pages/logistics/setting/_components/LogisticsTripAccordion.svelte
> +  let panel1Open = false;
panel1Open は不要となり削除され、アコーディオンの開閉で必要になった panelOpen が新たに追加となったことを確認しました。

2023-08-29 06:21 UTC, T-Ishikawa-R commented on web/app/src/pages/logistics/setting/_components/LogisticsRouteAccordion.svelte
> +        {route.name}
修正を確認しました。OKです。

2023-08-29 06:22 UTC, T-Ishikawa-R commented on web/app/src/pages/logistics/setting/_components/LogisticsTripAccordion.svelte
> +          <DataTable class="mb-3 mt-3" table$aria-label="People list" style="max-width: 100%;">
修正を確認しました。OKです。

2023-08-29 06:22 UTC, T-Ishikawa-R commented on web/app/src/pages/logistics/setting/_components/LogisticsTripAccordion.svelte
> +          <DataTable class="mb-3 mt-3" table$aria-label="People list" style="max-width: 100%;">
修正を確認しました。OKです。

2023-08-29 06:22 UTC, T-Ishikawa-R commented on web/app/src/pages/logistics/setting/_components/LogisticsTripAccordion.svelte
> +                  <Cell>{timetable.stop}</Cell>
修正を確認しました。OKです。

2023-08-29 06:23 UTC, T-Ishikawa-R commented on web/app/src/pages/logistics/setting/_components/LogisticsTripAccordion.svelte
> +            <p class="mt-2">{trip.capacity}</p>
修正を確認しました。OKです。

2023-08-29 06:23 UTC, T-Ishikawa-R commented on web/app/src/pages/logistics/setting/_components/LogisticsTripAccordion.svelte
> +          <DataTable class="mb-3 mt-3" table$aria-label="People list" style="max-width: 100%;">
修正を確認しました。OKです。

2023-08-29 06:24 UTC, T-Ishikawa-R commented on web/app/src/pages/logistics/setting/_components/LogisticsTripAccordion.svelte
> +<div class="ml-6">
修正を確認しました。OKです。

2023-08-29 06:28 UTC, T-Ishikawa-R commented on web/app/src/pages/logistics/setting/_components/LogisticsSettingForm.svelte
> +          <div style="display: flex; justify-content: center">
類似箇所として以下部分も修正お願いします。

```
  <div style="display: flex; justify-content: center">
    <CircularProgress style=" width: 32px;height: 160px;" indeterminate />
  </div>
```
↓
```
  <div class="flex justify-center">
    <CircularProgress class="h-[160px] w-[32px]" indeterminate />
  </div>
```

2023-08-29 06:30 UTC, T-Ishikawa-R commented on web/app/src/pages/logistics/setting/_components/LogisticsRouteAccordion.svelte
> +  <Accordion class="mt-4 outline outline-1 outline-offset-2 outline-[#000000]">
b7991978a21fe94faff84e8276e83b507d811d69 での修正を確認しました。OKです。

2023-08-29 06:34 UTC, T-Ishikawa-R commented on web/app/src/pages/logistics/setting/_components/LogisticsSettingForm.svelte
> +      <IconButton
アイコンが大きいため見出しの高さを一方のh1と揃うようにIconButtonにsize="button"としてみてください。

2023-08-30 00:09 UTC, YoshidaYuma commented on web/app/src/pages/logistics/setting/_components/LogisticsSettingForm.svelte
> +            <input type="text" class="justfy-center mx-3 flex" bind:value={routeName} />
https://github.com/NS-APU/BabaCafe/pull/58/commits/d3d4b6ce6a8bff603b9eca8dbec695d20938ff33
上記コミットにてTextFieldをContentに入れるようにしました。
また、TextFieldの下部に5ピクセルのマージンを取るためにContentタグのclassにmb-5の指定をしました。

2023-08-30 00:10 UTC, YoshidaYuma commented on web/app/src/pages/logistics/setting/_components/LogisticsSettingForm.svelte
> +        <div
https://github.com/NS-APU/BabaCafe/commit/d3d4b6ce6a8bff603b9eca8dbec695d20938ff33
上記コミットにて、いただいた例を参考に修正しました。

2023-08-30 00:11 UTC, YoshidaYuma commented on web/app/src/pages/logistics/setting/_components/LogisticsSettingForm.svelte
> +        {#if deliveryType === DELIVERY_TYPE.route}
https://github.com/NS-APU/BabaCafe/commit/d3d4b6ce6a8bff603b9eca8dbec695d20938ff33
上記コミットにてpタグを直前のdivに入れるように修正しました。

2023-08-30 00:12 UTC, YoshidaYuma commented on web/app/src/pages/logistics/setting/_components/LogisticsSettingForm.svelte
> +          <div style="display: flex; justify-content: center">
https://github.com/NS-APU/BabaCafe/commit/d3d4b6ce6a8bff603b9eca8dbec695d20938ff33
上記コミットにて、該当部分をtailwindに修正しました。

2023-08-30 00:14 UTC, YoshidaYuma commented on web/app/src/pages/logistics/setting/_components/LogisticsSettingForm.svelte
> +      <IconButton
https://github.com/NS-APU/BabaCafe/commit/d3d4b6ce6a8bff603b9eca8dbec695d20938ff33
上記コミットにてIconButtonにsize="button"と指定しました。
見出しの高さが揃うことも確認できました。
![image](https://github.com/NS-APU/BabaCafe/assets/89243430/cd32f036-15e8-46dc-a6b5-cfd1eedee4ee)

2023-08-30 00:54 UTC, T-Ishikawa-R commented on web/app/src/pages/logistics/setting/_components/LogisticsSettingForm.svelte
> +          <div style="display: flex; justify-content: center">
修正を確認しました。OKです。

2023-08-30 00:55 UTC, T-Ishikawa-R commented on web/app/src/pages/logistics/setting/_components/LogisticsSettingForm.svelte
> +      <IconButton
修正を確認しました。OKです。

2023-08-30 00:57 UTC, T-Ishikawa-R commented on web/app/src/pages/logistics/setting/_components/LogisticsSettingForm.svelte
> +            <input type="text" class="justfy-center mx-3 flex" bind:value={routeName} />
修正を確認しました。OKです。

2023-08-30 00:57 UTC, T-Ishikawa-R commented on web/app/src/pages/logistics/setting/_components/LogisticsSettingForm.svelte
> +        <div
修正を確認しました。OKです。

2023-08-30 00:58 UTC, T-Ishikawa-R commented on web/app/src/pages/logistics/setting/_components/LogisticsSettingForm.svelte
> +        {#if deliveryType === DELIVERY_TYPE.route}
修正を確認しました。OKです。

2023-08-30 00:58 UTC, T-Ishikawa-R approved these changes

2023-08-30 06:33 UTC, T-Ishikawa-R commented on web/app/src/pages/logistics/setting/_components/LogisticsSettingForm.svelte
> +      <Dialog selection bind:open={isUpdateDeliveryTypeDialogOpen} on:SMUIDialog:closed={onDialogClosedHandle}>
ダイアログをComponentに分離してはいかがでしょうか？
＃承認後にすいません

2023-08-30 07:58 UTC, T-Ishikawa-R commented on web/app/src/pages/logistics/setting/_components/LogisticsSettingForm.svelte
> +      <Dialog selection bind:open={isUpdateDeliveryTypeDialogOpen} on:SMUIDialog:closed={onDialogClosedHandle}>
5e0ea33bbcb5c0c6a06a44a5d02111d1653cfd51 で修正を確認しました。OKです。

2023-08-30 21:37 UTC, Mirenk approved these changes
大変遅くなり申し訳ありません．問題ありませんのでマージさせていただきます．

2023-08-30 21:45 UTC, Mirenk commented
先に物流候補をマージしてしまったことでコンフリクトが起こっているため，お手数おかけしますが解消の方お願いしてもよろしいでしょうか？

2023-08-31 01:57 UTC, YoshidaYuma commented
https://github.com/NS-APU/BabaCafe/pull/58/commits/738d417d01987d70063be7c56526ad72f37c9ead
上記コミットにてコンフリクト解消しました。
ただ、このPRで対応した実装の動作は確認できていますが、自分の環境だと配送便の候補が表示されなくなっています。（おそらく候補便を絞る時間帯によって発生する？）
![image](https://github.com/NS-APU/BabaCafe/assets/89243430/8749cd9a-2b13-4244-bf4f-0b31e4ef7117)
こちらについては石川さんの以下のPRにて対応してくださるとのことなので本PRでは対象外とします。
https://github.com/NS-APU/BabaCafe/pull/61

2023-08-31 07:37 UTC, Mirenk commented
対応ありがとうございます！マージいたします．
配送便のPRの方についても確認いたします．

2023-08-31 07:37 UTC, merged